import { Artist } from "@/definitions/artists";

export const artists: Artist[] = [
  {
    id: 1,
    name: "Sophia M.",
    image: "/images/artists/artist_1.jpeg",
    specialties: ["Hairstyling", "Wigs"],
    price: "$40",
    rating: 4.8,
    reviews: 120,
    availability: "Available Today",
  },
  {
    id: 2,
    name: "Janelle R.",
    image: "/images/artists/artist_2.jpeg",
    specialties: ["Nails"],
    price: "$25",
    rating: 4.6,
    reviews: 88,
    availability: "Tomorrow",
  },
  {
    id: 3,
    name: "Tasha B.",
    image: "/images/artists/artist_3.jpeg",
    specialties: ["Braids", "Installations"],
    price: "$55",
    rating: 4.9,
    reviews: 210,
    availability: "Available Today",
  },
  {
    id: 4,
    name: "Maya L.",
    image: "/images/artists/artist_4.jpeg",
    specialties: ["Installations"],
    price: "$70",
    rating: 4.7,
    reviews: 145,
    availability: "Next Week",
  },
  {
    id: 5,
    name: "Amber G.",
    image: "/images/artists/artist_5.jpeg",
    specialties: ["Wigs", "Hairstyling"],
    price: "$60",
    rating: 4.8,
    reviews: 167,
    availability: "Available Today",
  },
  {
    id: 6,
    name: "Chloe S.",
    image: "/images/artists/artist_6.jpeg",
    specialties: ["Hairstyling"],
    price: "$35",
    rating: 4.5,
    reviews: 90,
    availability: "Tomorrow",
  },
  {
    id: 7,
    name: "Naomi K.",
    image: "/images/artists/artist_7.jpeg",
    specialties: ["Nails", "Hairstyling"],
    price: "$45",
    rating: 4.7,
    reviews: 132,
    availability: "Available Today",
  },
  {
    id: 8,
    name: "Imani W.",
    image: "/images/artists/artist_8.jpeg",
    specialties: ["Braids"],
    price: "$50",
    rating: 4.9,
    reviews: 200,
    availability: "Fully Booked",
  },
  {
    id: 9,
    name: "Serena P.",
    image: "/images/artists/artist_9.jpeg",
    specialties: ["Installations", "Wigs"],
    price: "$75",
    rating: 4.6,
    reviews: 110,
    availability: "Next Week",
  },
  {
    id: 10,
    name: "Lena D.",
    image: "/images/artists/artist_10.jpeg",
    specialties: ["Wigs"],
    price: "$55",
    rating: 4.7,
    reviews: 156,
    availability: "Available Today",
  },
  {
    id: 11,
    name: "Amira Z.",
    image: "/images/artists/artist_11.jpeg",
    specialties: ["Hairstyling", "Braids"],
    price: "$48",
    rating: 4.9,
    reviews: 178,
    availability: "Tomorrow",
  },
  {
    id: 12,
    name: "Bella T.",
    image: "/images/artists/artist_12.jpeg",
    specialties: ["Nails"],
    price: "$30",
    rating: 4.6,
    reviews: 94,
    availability: "Available Today",
  },
  {
    id: 13,
    name: "Carmen J.",
    image: "/images/artists/artist_13.jpeg",
    specialties: ["Braids", "Installations"],
    price: "$65",
    rating: 4.8,
    reviews: 220,
    availability: "Fully Booked",
  },
  {
    id: 14,
    name: "Danielle V.",
    image: "/images/artists/artist_14.jpeg",
    specialties: ["Installations"],
    price: "$80",
    rating: 4.7,
    reviews: 134,
    availability: "Next Week",
  },
  {
    id: 15,
    name: "Ella F.",
    image: "/images/artists/artist_15.jpeg",
    specialties: ["Wigs", "Nails"],
    price: "$52",
    rating: 4.5,
    reviews: 99,
    availability: "Available Today",
  },
  {
    id: 16,
    name: "Faith C.",
    image: "/images/artists/artist_16.jpeg",
    specialties: ["Hairstyling"],
    price: "$42",
    rating: 4.7,
    reviews: 87,
    availability: "Tomorrow",
  },
  {
    id: 17,
    name: "Grace N.",
    image: "/images/artists/artist_17.jpeg",
    specialties: ["Nails"],
    price: "$28",
    rating: 4.9,
    reviews: 152,
    availability: "Available Today",
  },
  {
    id: 18,
    name: "Hannah O.",
    image: "/images/artists/artist_18.jpeg",
    specialties: ["Braids", "Hairstyling"],
    price: "$58",
    rating: 4.8,
    reviews: 176,
    availability: "Tomorrow",
  },
  {
    id: 19,
    name: "Isla R.",
    image: "/images/artists/artist_19.jpeg",
    specialties: ["Installations", "Wigs"],
    price: "$68",
    rating: 4.6,
    reviews: 122,
    availability: "Next Week",
  },
  {
    id: 20,
    name: "Jasmine P.",
    image: "/images/artists/artist_20.jpeg",
    specialties: ["Wigs"],
    price: "$57",
    rating: 4.9,
    reviews: 198,
    availability: "Available Today",
  },
  {
    id: 21,
    name: "Kylie B.",
    image: "/images/artists/artist_21.jpeg",
    specialties: ["Hairstyling"],
    price: "$38",
    rating: 4.6,
    reviews: 102,
    availability: "Tomorrow",
  },
  {
    id: 22,
    name: "Leah F.",
    image: "/images/artists/artist_22.jpeg",
    specialties: ["Nails", "Wigs"],
    price: "$50",
    rating: 4.8,
    reviews: 145,
    availability: "Available Today",
  },
  {
    id: 23,
    name: "Maya H.",
    image: "/images/artists/artist_23.jpeg",
    specialties: ["Braids"],
    price: "$62",
    rating: 4.7,
    reviews: 166,
    availability: "Fully Booked",
  },
  {
    id: 24,
    name: "Nora K.",
    image: "/images/artists/artist_24.jpeg",
    specialties: ["Installations"],
    price: "$72",
    rating: 4.5,
    reviews: 118,
    availability: "Next Week",
  },
  {
    id: 25,
    name: "Olivia S.",
    image: "/images/artists/artist_25.jpeg",
    specialties: ["Wigs", "Hairstyling"],
    price: "$63",
    rating: 4.9,
    reviews: 202,
    availability: "Available Today",
  },
  {
    id: 26,
    name: "Penelope A.",
    image: "/images/artists/artist_26.jpeg",
    specialties: ["Hairstyling", "Nails"],
    price: "$44",
    rating: 4.7,
    reviews: 111,
    availability: "Tomorrow",
  },
  /* {
    id: 27,
    name: "Quinn Z.",
    image: "/images/artists/artist_27.jpeg",
    specialties: ["Nails"],
    price: "$32",
    rating: 4.8,
    reviews: 137,
    availability: "Available Today",
  },
  {
    id: 28,
    name: "Riley V.",
    image: "/images/artists/artist_28.jpeg",
    specialties: ["Braids", "Installations"],
    price: "$66",
    rating: 4.9,
    reviews: 188,
    availability: "Fully Booked",
  },
  {
    id: 29,
    name: "Sienna G.",
    image: "/images/artists/artist_29.jpeg",
    specialties: ["Installations", "Wigs"],
    price: "$74",
    rating: 4.6,
    reviews: 130,
    availability: "Next Week",
  },
  {
    id: 30,
    name: "Tiana W.",
    image: "/images/artists/artist_30.jpeg",
    specialties: ["Wigs"],
    price: "$59",
    rating: 4.7,
    reviews: 160,
    availability: "Available Today",
  },
  {
    id: 31,
    name: "Uma L.",
    image: "/images/artists/artist_31.jpeg",
    specialties: ["Hairstyling"],
    price: "$39",
    rating: 4.8,
    reviews: 105,
    availability: "Tomorrow",
  },
  {
    id: 32,
    name: "Vanessa D.",
    image: "/images/artists/artist_32.jpeg",
    specialties: ["Nails"],
    price: "$27",
    rating: 4.7,
    reviews: 142,
    availability: "Available Today",
  },
  {
    id: 33,
    name: "Willow E.",
    image: "/images/artists/artist_33.jpeg",
    specialties: ["Braids"],
    price: "$60",
    rating: 4.8,
    reviews: 171,
    availability: "Tomorrow",
  },
  {
    id: 34,
    name: "Xena J.",
    image: "/images/artists/artist_34.jpeg",
    specialties: ["Installations"],
    price: "$76",
    rating: 4.7,
    reviews: 126,
    availability: "Next Week",
  },
  {
    id: 35,
    name: "Yara K.",
    image: "/images/artists/artist_35.jpeg",
    specialties: ["Wigs", "Hairstyling"],
    price: "$61",
    rating: 4.9,
    reviews: 209,
    availability: "Available Today",
  }, */
];
