import { Category, Service } from "@/definitions/services";

export const categories: Category[] = [
  {
    id: 1,
    name: "Hairstyling",
    image: "/images/hairstyling/dustin-chu.jpg",
  },
  {
    id: 2,
    name: "Nails",
    image: "/images/nails/lexie-janney.jpg",
  },
  {
    id: 3,
    name: "Conditioning",
    image: "/images/hairstyling/houcine-ncib.jpg",
  },
  {
    id: 4,
    name: "Extensions",
    image: "/images/hairstyling/houcine-ncib.jpg",
  },
  {
    id: 5,
    name: "Wigs",
    image: "/images/hairstyling/houcine-ncib.jpg",
  },
];

export const services: Service[] = [
  // --- Hairstyling ---
  {
    id: 1,
    name: "Classic Men's Cut",
    artist: "John Doe",
    price: "$20",
    image: "/images/hairstyling/ben-iwara.jpg",
    description: "A timeless men's haircut with precision styling.",
    category: "Hairstyling",
  },
  {
    id: 2,
    name: "Skin Fade",
    artist: "Michael Fadez",
    price: "$25",
    image: "/images/hairstyling/airam-dato.jpg",
    description: "Sharp fade with detailed blending.",
    category: "Hairstyling",
  },
  {
    id: 3,
    name: "Bridal Updo",
    artist: "Sophia Styles",
    price: "$90",
    image: "/images/hairstyling/olivier-rule.jpg",
    description: "Elegant updo perfect for weddings and formal events.",
    category: "Hairstyling",
  },
  {
    id: 4,
    name: "Beach Waves",
    artist: "Ava Styles",
    price: "$40",
    image: "/images/hairstyling/luke-southern.jpg",
    description: "Soft waves for a relaxed beachy look.",
    category: "Hairstyling",
  },
  {
    id: 5,
    name: "Straightening",
    artist: "Noah HairPro",
    price: "$50",
    image: "/images/hairstyling/gilda-gonzalez.jpg",
    description: "Silky straight hair with heat-protection treatment.",
    category: "Hairstyling",
  },
  {
    id: 6,
    name: "Children's Cut",
    artist: "Emma Barber",
    price: "$15",
    image: "/images/hairstyling/dwayne-joe.jpg",
    description: "Fun and stylish haircut for children.",
    category: "Hairstyling",
  },

  // --- Nails ---
  {
    id: 7,
    name: "Classic Manicure",
    artist: "Nina Nails",
    price: "$25",
    image: "/images/nails/nails_1.jpg",
    description: "Clean and classic manicure with polish.",
    category: "Nails",
  },
  {
    id: 8,
    name: "Gel Polish",
    artist: "Mia Shine",
    price: "$35",
    image: "/images/nails/nails_2.jpg",
    description: "Long-lasting gel polish for glossy nails.",
    category: "Nails",
  },
  {
    id: 9,
    name: "French Tips",
    artist: "Liam Nails",
    price: "$30",
    image: "/images/nails/nails_3.jpg",
    description: "Classic French tips with precision finish.",
    category: "Nails",
  },
  {
    id: 10,
    name: "Pedicure",
    artist: "Olivia Toes",
    price: "$40",
    image: "/images/nails/nails_4.jpg",
    description: "Relaxing pedicure with exfoliation and polish.",
    category: "Nails",
  },
  {
    id: 11,
    name: "Acrylic Full Set",
    artist: "Sophia Gloss",
    price: "$55",
    image: "/images/nails/nails_5.jpg",
    description: "Durable and stylish acrylic nail extensions.",
    category: "Nails",
  },
  {
    id: 12,
    name: "Nail Art Design",
    artist: "Ella Art",
    price: "$20",
    image: "/images/nails/nails_6.jpg",
    description: "Custom nail art design to match your style.",
    category: "Nails",
  },

  // --- Conditioning ---
  {
    id: 13,
    name: "Keratin Treatment",
    artist: "Sophia Smooth",
    price: "$120",
    image: "/images/relaxed/relaxed_1.jpeg",
    description: "Frizz-control and smoothening keratin service.",
    category: "Conditioning",
  },
  {
    id: 14,
    name: "Hair Spa",
    artist: "Mia Relax",
    price: "$55",
    image: "/images/relaxed/relaxed_2.jpeg",
    description: "Deep nourishment and relaxation for your hair.",
    category: "Conditioning",
  },
  {
    id: 15,
    name: "Scalp Massage",
    artist: "Ethan Care",
    price: "$35",
    image: "/images/relaxed/relaxed_3.jpeg",
    description: "Stress-relieving scalp massage with oils.",
    category: "Conditioning",
  },
  {
    id: 16,
    name: "Deep Conditioning",
    artist: "Ava Shine",
    price: "$45",
    image: "/images/relaxed/relaxed_4.jpeg",
    description: "Hydrating treatment for dry, damaged hair.",
    category: "Conditioning",
  },
  {
    id: 17,
    name: "Protein Treatment",
    artist: "Noah Strength",
    price: "$50",
    image: "/images/relaxed/relaxed_5.jpeg",
    description: "Protein boost to strengthen hair fibers.",
    category: "Conditioning",
  },
  {
    id: 18,
    name: "Moisture Boost",
    artist: "Ella Hydrate",
    price: "$40",
    image: "/images/relaxed/relaxed_6.jpeg",
    description: "Intense moisture therapy for dull hair.",
    category: "Conditioning",
  },

  // --- Extensions ---
  {
    id: 19,
    name: "Clip-In Extensions",
    artist: "Lily Luxe",
    price: "$150",
    image: "/images/extensions/clipin.jpg",
    description: "Quick and easy clip-in extensions for volume.",
    category: "Extensions",
  },
  {
    id: 20,
    name: "Tape-In Extensions",
    artist: "Sophia Glam",
    price: "$180",
    image: "/images/extensions/tapein.jpg",
    description: "Seamless tape-in extensions with natural look.",
    category: "Extensions",
  },
  {
    id: 21,
    name: "Sew-In Extensions",
    artist: "Mia Weave",
    price: "$200",
    image: "/images/extensions/sewin.jpg",
    description: "Durable sew-in for added length and fullness.",
    category: "Extensions",
  },
  {
    id: 22,
    name: "Fusion Extensions",
    artist: "Olivia Elite",
    price: "$250",
    image: "/images/extensions/fusion.jpg",
    description: "Premium keratin-bond fusion extensions.",
    category: "Extensions",
  },
  {
    id: 23,
    name: "Micro-Link Extensions",
    artist: "Emma Links",
    price: "$220",
    image: "/images/extensions/microlink.jpg",
    description: "Reusable micro-link extensions with flexibility.",
    category: "Extensions",
  },
  {
    id: 24,
    name: "Extension Removal",
    artist: "Ava Care",
    price: "$80",
    image: "/images/extensions/removal.jpg",
    description: "Safe and professional extension removal.",
    category: "Extensions",
  },

  // --- Wigs ---
  {
    id: 25,
    name: "Custom Wig Install",
    artist: "Liam Stylist",
    price: "$180",
    image: "/images/wigs/custom.jpg",
    description: "Personalized wig installation for a natural look.",
    category: "Wigs",
  },
  {
    id: 26,
    name: "Lace Front Wig",
    artist: "Sophia Lace",
    price: "$200",
    image: "/images/wigs/lacefront.jpg",
    description: "High-quality lace front wig styling.",
    category: "Wigs",
  },
  {
    id: 27,
    name: "Wig Styling",
    artist: "Mia Style",
    price: "$100",
    image: "/images/wigs/styling.jpg",
    description: "Custom styling to refresh your wig look.",
    category: "Wigs",
  },
  {
    id: 28,
    name: "Wig Coloring",
    artist: "Olivia Color",
    price: "$150",
    image: "/images/wigs/color.jpg",
    description: "Professional wig coloring services.",
    category: "Wigs",
  },
  {
    id: 29,
    name: "Wig Maintenance",
    artist: "Emma Care",
    price: "$70",
    image: "/images/wigs/maintenance.jpg",
    description: "Keep your wig fresh with deep cleaning and care.",
    category: "Wigs",
  },
  {
    id: 30,
    name: "Synthetic Wig Install",
    artist: "Ava Trend",
    price: "$120",
    image: "/images/wigs/synthetic.jpg",
    description: "Affordable synthetic wig installation service.",
    category: "Wigs",
  },
];

export const topBookedServices: Service[] = services.slice(0, 6);
